# Generated by Django 3.1.4 on 2020-12-24 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatizationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(blank=True, null=True)),
                ('automatical_fabric_count', models.IntegerField(blank=True, null=True)),
                ('simple_fabric_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EGPRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egp_count', models.IntegerField(blank=True, null=True)),
                ('egp_price', models.IntegerField(blank=True, null=True)),
                ('bank_response', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ESMRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esm_count', models.IntegerField(blank=True, null=True)),
                ('esm_price', models.IntegerField(blank=True, null=True)),
                ('bank_response', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('players_count', models.IntegerField()),
                ('step', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('loan_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.IntegerField(blank=True, null=True)),
                ('auto_fabric_count', models.IntegerField(blank=True, null=True)),
                ('simple_fabric_count', models.IntegerField(blank=True, null=True)),
                ('esm', models.IntegerField(blank=True, null=True)),
                ('egp', models.IntegerField(blank=True, null=True)),
                ('egp_request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.egprequest')),
                ('esm_request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.esmrequest')),
                ('loan_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.loan')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='BuildRequestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_player_id', to='game.playergameinfo')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.automatizationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='AutomatizationRequestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_player_id', to='game.playergameinfo')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.buildrequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playergameinfo',
            constraint=models.UniqueConstraint(fields=('player_id', 'room_id'), name='unique_game_info'),
        ),
        migrations.AddConstraint(
            model_name='buildrequestlist',
            constraint=models.UniqueConstraint(fields=('player_info_id', 'request_id'), name='unique_in_build_request'),
        ),
        migrations.AddConstraint(
            model_name='automatizationrequestlist',
            constraint=models.UniqueConstraint(fields=('player_info_id', 'request_id'), name='unique_in_auto_request'),
        ),
    ]
