# Generated by Django 3.1.4 on 2020-12-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='senior_player',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
