# Generated by Django 3.1.4 on 2021-01-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_playergameinfo_senior_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='level',
            field=models.IntegerField(default=3, null=True),
        ),
    ]
