# Generated by Django 3.1.4 on 2021-01-16 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatizationrequestlist',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.automatizationrequest'),
        ),
        migrations.AlterField(
            model_name='buildrequestlist',
            name='request_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.buildrequest'),
        ),
    ]
