# Generated by Django 3.1.4 on 2021-01-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210116_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_stage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergameinfo',
            name='player_turn_finish',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
