# Generated by Django 3.1.4 on 2021-01-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210117_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='senioring',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
