# Generated by Django 3.1.4 on 2021-01-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_playergameinfo_senioring'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergameinfo',
            name='esm_produce',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
