# Generated by Django 3.1.4 on 2021-01-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_playergameinfo_esm_produce'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
